name: NestJS E2E Tests

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  e2e-tests:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Setup Docker
      uses: docker/setup-buildx-action@v3
      
    - name: Start Docker Compose services
      run: |
        docker compose -f docker-compose.yml up -d test-db
        # Wait for PostgreSQL to be ready
        echo "Waiting for PostgreSQL to be ready..."
        sleep 10
        
    - name: Run E2E tests
      run: npm run test:e2e
      env:
        DB_USER: ${{ vars.DB_USER }}
        DB_NAME: ${{ vars.DB_NAME }}
        DB_PASSWORD: ${{ vars.DB_PASSWORD }}
        DB_PORT: ${{ vars.DB_PORT }}
        DB_HOST: ${{ vars.DB_HOST }}
        DATABASE_URL: ${{ vars.DATABASE_URL }}
        NODE_ENV: ${{ vars.NODE_ENV }}
        SECRET_KEY: ${{ vars.SECRET_KEY || 'secretkey' }}
